// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK76NhOAhWedq9TQLTvp3g7CP5t8mbdDE',
    appId: '1:691814945722:web:c4b66b4e9302a2be788383',
    messagingSenderId: '691814945722',
    projectId: 'travel2-5fdf5',
    authDomain: 'travel2-5fdf5.firebaseapp.com',
    storageBucket: 'travel2-5fdf5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHDj0TVw8WetTeUbK6T6FGJoa_oT2krJQ',
    appId: '1:691814945722:android:173e0e57e556722e788383',
    messagingSenderId: '691814945722',
    projectId: 'travel2-5fdf5',
    storageBucket: 'travel2-5fdf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALkJ1wgVbRy6XaGlxmyyZNGNBqOoOjBhE',
    appId: '1:691814945722:ios:f3938fe5fa62a906788383',
    messagingSenderId: '691814945722',
    projectId: 'travel2-5fdf5',
    storageBucket: 'travel2-5fdf5.firebasestorage.app',
    iosBundleId: 'com.example.travel2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALkJ1wgVbRy6XaGlxmyyZNGNBqOoOjBhE',
    appId: '1:691814945722:ios:f3938fe5fa62a906788383',
    messagingSenderId: '691814945722',
    projectId: 'travel2-5fdf5',
    storageBucket: 'travel2-5fdf5.firebasestorage.app',
    iosBundleId: 'com.example.travel2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK76NhOAhWedq9TQLTvp3g7CP5t8mbdDE',
    appId: '1:691814945722:web:27c81f6fee60ba00788383',
    messagingSenderId: '691814945722',
    projectId: 'travel2-5fdf5',
    authDomain: 'travel2-5fdf5.firebaseapp.com',
    storageBucket: 'travel2-5fdf5.firebasestorage.app',
  );

}